Modify the welcoming message
ArabR/ArabR-Website pull request #17
Opened 2022-04-07 14:12 UTC by BatoolMM

Simple PR to modify the welcoming page!
Can we possibly list all useR groups and R-Ladies group on the landing page or everything should be in a post?

2022-04-07 17:53 UTC, BatoolMM commented
The CI is failing - it can't deploy it!

<img src="https://media3.giphy.com/media/l2JhtKtDWYNKdRpoA/giphy.gif"/>

2022-04-09 12:10 UTC, Hussain-Alsalman commented
Tags need to be in quotation marks. Refer to [this](https://github.com/ArabR/ArabR-Website/blob/main/CONTRIBUTING.md#how-to-add-a-post) to learn more about the theme parameters

2022-04-09 15:19 UTC, Hussain-Alsalman requested changes

2022-04-09 15:19 UTC, Hussain-Alsalman commented on content/posts/Welcoming-Messege.en.md
> +tags: vision
Tags need to be in quotation marks. Refer to [this](https://github.com/ArabR/ArabR-Website/blob/main/CONTRIBUTING.md#how-to-add-a-post) to learn more about the theme parameters

2022-04-10 13:44 UTC, Hussain-Alsalman commented on content/posts/Welcoming-Messege.en.md
> +tags: vision
Sorry I had not test your PR until now. The problem can be fixed by making tags a list. It should look something like this 
```
tags: 
     - "vision"
```
It seems that quotations are optional.

2022-04-20 21:31 UTC, alswajiab commented
As Hussain mentioned, you're missing `-` in your commit.
```
tags: 
     - "vision"
```

2022-04-20 21:39 UTC, BatoolMM commented
Thank you @alswajiab and @Hussain-Alsalman!

2022-04-20 21:39 UTC, merged